In [108]:
from maskmm.ipstartup import *
from maskmm.utils import visualize
from maskmm.samples.nuke.config import Config
from maskmm.baseline import rngreset
from nuke import *

class Config(Config):
    NAME = "mm"
    STEPS_PER_EPOCH = 3
    VALIDATION_STEPS = 1
    
    GPU_COUNT=1
    COMPAT = True
    AUGMENT = False
    SHUFFLE = False
    IMAGES_PER_GPU=1
    #HEAD = False
config = Config()
rngreset()

[root:INFO]:starting (cellevents.py:36, time=18:11)


time: 26.8 ms


In [109]:
learn = get_learn(config)

[root:INFO]:starting (cellevents.py:36, time=18:11)


time: 373 ms


In [110]:
learn.fit(1, lr=.01)

[root:INFO]:starting (cellevents.py:36, time=18:11)


AttributeError: 'numpy.ndarray' object has no attribute 'gt'

time: 97.8 ms


In [60]:
[image, image_metas, rpn_match, rpn_bbox, gt_class_ids, gt_boxes, gt_masks], _ = learn.data.train_ds[13]

[root:INFO]:starting (cellevents.py:36, time=17:53)


time: 538 ms


In [121]:
m = gt_masks.permute(1,2,0).cpu().numpy()
(m>0).nonzero()

[root:INFO]:starting (cellevents.py:36, time=18:13)


(array([ 0,  0,  0, ..., 55, 55, 55]),
 array([ 0,  0,  0, ..., 55, 55, 55]),
 array([ 3,  8, 12, ...,  7, 11, 26]))

time: 4.17 ms


In [107]:
gt_masks.gt(0).nonzero()[:,0].unique()

[root:INFO]:starting (cellevents.py:36, time=18:03)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 22, 23, 24, 25, 26])

time: 4.76 ms


In [80]:
for x in learn.data.train_ds.load_mask(13)[0]:
    print(x.sum())

[root:INFO]:starting (cellevents.py:36, time=17:57)


54060
53550
54570
54315
54060
53550
53550
52785
53040
52530
52020
51255
49980
49470
47430
46665
45645
44115
42840
41055
38760
37485
35445
31110
29580
28050
26775
25755
24480
22185
21165
19125
15555
13260
12750
11985
10965
9690
8415
7395
5355
3315
0
0
0
0
0
0
0
0
0
0
0
0
0
765
3315
4845
5865
6630
7140
7650
8160
8670
8925
9180
9435
9690
9945
10710
12495
14280
15555
16575
17850
18615
19380
19380
19890
20400
20910
21675
21930
22695
23205
23715
24225
24990
25245
25500
25500
25755
25755
25500
25500
25245
25245
24990
24480
23970
23205
22695
22185
21930
22950
22950
22950
22440
21165
19890
19890
19125
19125
19380
19380
19125
19125
18615
18870
17850
17085
17085
16830
16830
16575
16320
16320
15810
15555
15045
14025
17595
18870
17850
19635
20910
21930
22695
23460
24480
25245
26010
26520
27285
27540
28815
28560
29070
29325
29580
29835
29835
29580
29835
29325
32130
32895
33405
33915
34170
33915
34170
33405
32130
30855
29580
27795
26775
22440
19890
20400
20655
21165
21165
21165
21420
21420
21675
2142

In [72]:
from maskmm.utils.batch import *
len(unpack([pad(gt_masks, 100).unsqueeze(0)])[0][0])

[root:INFO]:starting (cellevents.py:36, time=17:54)


26

time: 5.56 ms


In [ ]:
learn.recorder.plot_losses()